export interface Player {
  name: string;
  shortName: string;
  position: 'GK' | 'DEF' | 'MID' | 'FWD';
  starter: boolean;
}

export type Squad = Player[];

const BRESIL: Squad = [
  // Titulaires (4-3-3)
  { name: 'Alisson', shortName: 'Alisson', position: 'GK', starter: true },
  { name: 'Danilo', shortName: 'Danilo', position: 'DEF', starter: true },
  { name: 'Éder Militão', shortName: 'Militão', position: 'DEF', starter: true },
  { name: 'Marquinhos', shortName: 'Marquinhos', position: 'DEF', starter: true },
  { name: 'Guilherme Arana', shortName: 'Arana', position: 'DEF', starter: true },
  { name: 'Casemiro', shortName: 'Casemiro', position: 'MID', starter: true },
  { name: 'Bruno Guimarães', shortName: 'Guimarães', position: 'MID', starter: true },
  { name: 'Lucas Paquetá', shortName: 'Paquetá', position: 'MID', starter: true },
  { name: 'Raphinha', shortName: 'Raphinha', position: 'FWD', starter: true },
  { name: 'Vinicius Jr', shortName: 'Vinicius Jr', position: 'FWD', starter: true },
  { name: 'Rodrygo', shortName: 'Rodrygo', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Ederson', shortName: 'Ederson', position: 'GK', starter: false },
  { name: 'Bento', shortName: 'Bento', position: 'GK', starter: false },
  { name: 'Gabriel Magalhães', shortName: 'G. Magalhães', position: 'DEF', starter: false },
  { name: 'Wendell', shortName: 'Wendell', position: 'DEF', starter: false },
  { name: 'Alex Telles', shortName: 'Telles', position: 'DEF', starter: false },
  { name: 'Gerson', shortName: 'Gerson', position: 'MID', starter: false },
  { name: 'Andreas Pereira', shortName: 'A. Pereira', position: 'MID', starter: false },
  { name: 'Joelinton', shortName: 'Joelinton', position: 'MID', starter: false },
  { name: 'Douglas Luiz', shortName: 'D. Luiz', position: 'MID', starter: false },
  { name: 'Gabriel Martinelli', shortName: 'Martinelli', position: 'FWD', starter: false },
  { name: 'Endrick', shortName: 'Endrick', position: 'FWD', starter: false },
  { name: 'Savinho', shortName: 'Savinho', position: 'FWD', starter: false },
  { name: 'Gabriel Jesus', shortName: 'G. Jesus', position: 'FWD', starter: false },
  { name: 'Matheus Cunha', shortName: 'M. Cunha', position: 'FWD', starter: false },
  { name: 'Richarlison', shortName: 'Richarlison', position: 'FWD', starter: false },
];

const MAROC: Squad = [
  // Titulaires (4-3-3)
  { name: 'Yassine Bounou', shortName: 'Bono', position: 'GK', starter: true },
  { name: 'Achraf Hakimi', shortName: 'Hakimi', position: 'DEF', starter: true },
  { name: 'Nayef Aguerd', shortName: 'Aguerd', position: 'DEF', starter: true },
  { name: 'Romain Saïss', shortName: 'Saïss', position: 'DEF', starter: true },
  { name: 'Noussair Mazraoui', shortName: 'Mazraoui', position: 'DEF', starter: true },
  { name: 'Sofyan Amrabat', shortName: 'Amrabat', position: 'MID', starter: true },
  { name: 'Azzedine Ounahi', shortName: 'Ounahi', position: 'MID', starter: true },
  { name: 'Bilal El Khannouss', shortName: 'El Khannouss', position: 'MID', starter: true },
  { name: 'Hakim Ziyech', shortName: 'Ziyech', position: 'FWD', starter: true },
  { name: 'Youssef En-Nesyri', shortName: 'En-Nesyri', position: 'FWD', starter: true },
  { name: 'Soufiane Boufal', shortName: 'Boufal', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Munir Mohamedi', shortName: 'Mohamedi', position: 'GK', starter: false },
  { name: 'Anas Zniti', shortName: 'Zniti', position: 'GK', starter: false },
  { name: 'Jawad El Yamiq', shortName: 'El Yamiq', position: 'DEF', starter: false },
  { name: 'Adam Masina', shortName: 'Masina', position: 'DEF', starter: false },
  { name: 'Badr Benoun', shortName: 'Benoun', position: 'DEF', starter: false },
  { name: 'Selim Amallah', shortName: 'Amallah', position: 'MID', starter: false },
  { name: 'Abdelhamid Sabiri', shortName: 'Sabiri', position: 'MID', starter: false },
  { name: 'Ilias Chair', shortName: 'I. Chair', position: 'MID', starter: false },
  { name: 'Abde Ezzalzouli', shortName: 'Abde', position: 'FWD', starter: false },
  { name: 'Brahim Díaz', shortName: 'B. Díaz', position: 'FWD', starter: false },
  { name: 'Ayoub El Kaabi', shortName: 'El Kaabi', position: 'FWD', starter: false },
  { name: 'Zakaria Aboukhlal', shortName: 'Aboukhlal', position: 'FWD', starter: false },
  { name: 'Anass Zaroury', shortName: 'Zaroury', position: 'FWD', starter: false },
  { name: 'Ryan Mmaee', shortName: 'Mmaee', position: 'FWD', starter: false },
];

const BELGIQUE: Squad = [
  // Titulaires (4-3-3)
  { name: 'Thibaut Courtois', shortName: 'Courtois', position: 'GK', starter: true },
  { name: 'Timothy Castagne', shortName: 'Castagne', position: 'DEF', starter: true },
  { name: 'Wout Faes', shortName: 'Faes', position: 'DEF', starter: true },
  { name: 'Jan Vertonghen', shortName: 'Vertonghen', position: 'DEF', starter: true },
  { name: 'Arthur Theate', shortName: 'Theate', position: 'DEF', starter: true },
  { name: 'Kevin De Bruyne', shortName: 'De Bruyne', position: 'MID', starter: true },
  { name: 'Youri Tielemans', shortName: 'Tielemans', position: 'MID', starter: true },
  { name: 'Hans Vanaken', shortName: 'Vanaken', position: 'MID', starter: true },
  { name: 'Jérémy Doku', shortName: 'Doku', position: 'FWD', starter: true },
  { name: 'Romelu Lukaku', shortName: 'Lukaku', position: 'FWD', starter: true },
  { name: 'Charles De Ketelaere', shortName: 'De Ketelaere', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Koen Casteels', shortName: 'Casteels', position: 'GK', starter: false },
  { name: 'Simon Mignolet', shortName: 'Mignolet', position: 'GK', starter: false },
  { name: 'Zeno Debast', shortName: 'Debast', position: 'DEF', starter: false },
  { name: 'Brandon Mechele', shortName: 'Mechele', position: 'DEF', starter: false },
  { name: 'Axel Witsel', shortName: 'Witsel', position: 'MID', starter: false },
  { name: 'Amadou Onana', shortName: 'Onana', position: 'MID', starter: false },
  { name: 'Orel Mangala', shortName: 'Mangala', position: 'MID', starter: false },
  { name: 'Thorgan Hazard', shortName: 'T. Hazard', position: 'MID', starter: false },
  { name: 'Yannick Carrasco', shortName: 'Carrasco', position: 'FWD', starter: false },
  { name: 'Leandro Trossard', shortName: 'Trossard', position: 'FWD', starter: false },
  { name: 'Lois Openda', shortName: 'Openda', position: 'FWD', starter: false },
  { name: 'Michy Batshuayi', shortName: 'Batshuayi', position: 'FWD', starter: false },
  { name: 'Dodi Lukebakio', shortName: 'Lukebakio', position: 'FWD', starter: false },
  { name: 'Johan Bakayoko', shortName: 'Bakayoko', position: 'FWD', starter: false },
];

const EGYPTE: Squad = [
  // Titulaires (4-2-3-1)
  { name: 'Mohamed El-Shenawy', shortName: 'El-Shenawy', position: 'GK', starter: true },
  { name: 'Omar Gaber', shortName: 'O. Gaber', position: 'DEF', starter: true },
  { name: 'Ahmed Hegazi', shortName: 'Hegazi', position: 'DEF', starter: true },
  { name: 'Hamdi Fathi', shortName: 'H. Fathi', position: 'DEF', starter: true },
  { name: 'Ahmed Fatouh', shortName: 'Fatouh', position: 'DEF', starter: true },
  { name: 'Mohamed Elneny', shortName: 'Elneny', position: 'MID', starter: true },
  { name: 'Tarek Hamed', shortName: 'T. Hamed', position: 'MID', starter: true },
  { name: 'Emam Ashour', shortName: 'E. Ashour', position: 'MID', starter: true },
  { name: 'Mohamed Salah', shortName: 'Salah', position: 'FWD', starter: true },
  { name: 'Omar Marmoush', shortName: 'Marmoush', position: 'FWD', starter: true },
  { name: 'Mostafa Mohamed', shortName: 'M. Mohamed', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Mohamed Abougabal', shortName: 'Abougabal', position: 'GK', starter: false },
  { name: 'Ahmed El-Shennawy', shortName: 'A. Shennawy', position: 'GK', starter: false },
  { name: 'Karim Fouad', shortName: 'K. Fouad', position: 'DEF', starter: false },
  { name: 'Mahmoud Alaa', shortName: 'M. Alaa', position: 'DEF', starter: false },
  { name: 'Amr El-Soulia', shortName: 'El-Soulia', position: 'MID', starter: false },
  { name: 'Ramadan Sobhi', shortName: 'R. Sobhi', position: 'MID', starter: false },
  { name: 'Ahmed Sayed Zizo', shortName: 'Zizo', position: 'MID', starter: false },
  { name: 'Marwan Hamdy', shortName: 'M. Hamdy', position: 'MID', starter: false },
  { name: 'Ahmed Kouka', shortName: 'A. Kouka', position: 'FWD', starter: false },
  { name: 'Akram Tawfik', shortName: 'A. Tawfik', position: 'FWD', starter: false },
  { name: 'Mohamed Sherif', shortName: 'M. Sherif', position: 'FWD', starter: false },
  { name: 'Trezeguet', shortName: 'Trezeguet', position: 'FWD', starter: false },
];

const FRANCE: Squad = [
  // Titulaires (4-3-3)
  { name: 'Mike Maignan', shortName: 'Maignan', position: 'GK', starter: true },
  { name: 'Benjamin Pavard', shortName: 'Pavard', position: 'DEF', starter: true },
  { name: 'William Saliba', shortName: 'Saliba', position: 'DEF', starter: true },
  { name: 'Dayot Upamecano', shortName: 'Upamecano', position: 'DEF', starter: true },
  { name: 'Theo Hernandez', shortName: 'T. Hernandez', position: 'DEF', starter: true },
  { name: 'Aurelien Tchouameni', shortName: 'Tchouameni', position: 'MID', starter: true },
  { name: 'Eduardo Camavinga', shortName: 'Camavinga', position: 'MID', starter: true },
  { name: 'Antoine Griezmann', shortName: 'Griezmann', position: 'MID', starter: true },
  { name: 'Ousmane Dembélé', shortName: 'Dembélé', position: 'FWD', starter: true },
  { name: 'Kylian Mbappé', shortName: 'Mbappé', position: 'FWD', starter: true },
  { name: 'Marcus Thuram', shortName: 'M. Thuram', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Alphonse Areola', shortName: 'Areola', position: 'GK', starter: false },
  { name: 'Brice Samba', shortName: 'Samba', position: 'GK', starter: false },
  { name: 'Jonathan Clauss', shortName: 'Clauss', position: 'DEF', starter: false },
  { name: 'Ibrahima Konaté', shortName: 'Konaté', position: 'DEF', starter: false },
  { name: 'Lucas Hernandez', shortName: 'L. Hernandez', position: 'DEF', starter: false },
  { name: 'Matteo Guendouzi', shortName: 'Guendouzi', position: 'MID', starter: false },
  { name: 'Adrien Rabiot', shortName: 'Rabiot', position: 'MID', starter: false },
  { name: 'Youssouf Fofana', shortName: 'Fofana', position: 'MID', starter: false },
  { name: 'Christopher Nkunku', shortName: 'Nkunku', position: 'FWD', starter: false },
  { name: 'Randal Kolo Muani', shortName: 'Kolo Muani', position: 'FWD', starter: false },
  { name: 'Olivier Giroud', shortName: 'Giroud', position: 'FWD', starter: false },
  { name: 'Michael Olise', shortName: 'Olise', position: 'FWD', starter: false },
  { name: 'Warren Zaïre-Emery', shortName: 'Zaïre-Emery', position: 'MID', starter: false },
];

const SENEGAL: Squad = [
  // Titulaires (4-3-3)
  { name: 'Edouard Mendy', shortName: 'E. Mendy', position: 'GK', starter: true },
  { name: 'Bouna Sarr', shortName: 'B. Sarr', position: 'DEF', starter: true },
  { name: 'Kalidou Koulibaly', shortName: 'Koulibaly', position: 'DEF', starter: true },
  { name: 'Abdou Diallo', shortName: 'A. Diallo', position: 'DEF', starter: true },
  { name: 'Fodé Ballo-Touré', shortName: 'Ballo-Touré', position: 'DEF', starter: true },
  { name: 'Idrissa Gueye', shortName: 'I. Gueye', position: 'MID', starter: true },
  { name: 'Nampalys Mendy', shortName: 'N. Mendy', position: 'MID', starter: true },
  { name: 'Cheikhou Kouyaté', shortName: 'Kouyaté', position: 'MID', starter: true },
  { name: 'Ismaïla Sarr', shortName: 'I. Sarr', position: 'FWD', starter: true },
  { name: 'Sadio Mané', shortName: 'Mané', position: 'FWD', starter: true },
  { name: 'Boulaye Dia', shortName: 'B. Dia', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Alfred Gomis', shortName: 'Gomis', position: 'GK', starter: false },
  { name: 'Seny Dieng', shortName: 'S. Dieng', position: 'GK', starter: false },
  { name: 'Saliou Ciss', shortName: 'S. Ciss', position: 'DEF', starter: false },
  { name: 'Formose Mendy', shortName: 'F. Mendy', position: 'DEF', starter: false },
  { name: 'Moussa Niakhaté', shortName: 'Niakhaté', position: 'DEF', starter: false },
  { name: 'Pape Gueye', shortName: 'P. Gueye', position: 'MID', starter: false },
  { name: 'Krepin Diatta', shortName: 'K. Diatta', position: 'MID', starter: false },
  { name: 'Pathé Ciss', shortName: 'P. Ciss', position: 'MID', starter: false },
  { name: 'Habib Diallo', shortName: 'H. Diallo', position: 'FWD', starter: false },
  { name: 'Famara Diédhiou', shortName: 'Diédhiou', position: 'FWD', starter: false },
  { name: 'Nicolas Jackson', shortName: 'N. Jackson', position: 'FWD', starter: false },
  { name: 'Lamine Camara', shortName: 'L. Camara', position: 'MID', starter: false },
];

const PORTUGAL: Squad = [
  // Titulaires (4-3-3)
  { name: 'Diogo Costa', shortName: 'D. Costa', position: 'GK', starter: true },
  { name: 'Diogo Dalot', shortName: 'Dalot', position: 'DEF', starter: true },
  { name: 'Rúben Dias', shortName: 'R. Dias', position: 'DEF', starter: true },
  { name: 'Gonçalo Inácio', shortName: 'G. Inácio', position: 'DEF', starter: true },
  { name: 'Nuno Mendes', shortName: 'N. Mendes', position: 'DEF', starter: true },
  { name: 'João Palhinha', shortName: 'Palhinha', position: 'MID', starter: true },
  { name: 'Vitinha', shortName: 'Vitinha', position: 'MID', starter: true },
  { name: 'Bruno Fernandes', shortName: 'B. Fernandes', position: 'MID', starter: true },
  { name: 'Bernardo Silva', shortName: 'B. Silva', position: 'FWD', starter: true },
  { name: 'Gonçalo Ramos', shortName: 'G. Ramos', position: 'FWD', starter: true },
  { name: 'Rafael Leão', shortName: 'R. Leão', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'José Sá', shortName: 'J. Sá', position: 'GK', starter: false },
  { name: 'Rui Patrício', shortName: 'R. Patrício', position: 'GK', starter: false },
  { name: 'João Cancelo', shortName: 'J. Cancelo', position: 'DEF', starter: false },
  { name: 'Pepe', shortName: 'Pepe', position: 'DEF', starter: false },
  { name: 'António Silva', shortName: 'A. Silva', position: 'DEF', starter: false },
  { name: 'Rúben Neves', shortName: 'R. Neves', position: 'MID', starter: false },
  { name: 'Otávio', shortName: 'Otávio', position: 'MID', starter: false },
  { name: 'João Félix', shortName: 'J. Félix', position: 'FWD', starter: false },
  { name: 'Pedro Neto', shortName: 'P. Neto', position: 'FWD', starter: false },
  { name: 'Diogo Jota', shortName: 'D. Jota', position: 'FWD', starter: false },
  { name: 'Cristiano Ronaldo', shortName: 'Ronaldo', position: 'FWD', starter: false },
  { name: 'Francisco Trincão', shortName: 'Trincão', position: 'FWD', starter: false },
  { name: 'Mateus Fernandes', shortName: 'M. Fernandes', position: 'MID', starter: false },
];

const RD_CONGO: Squad = [
  // Titulaires (4-3-3)
  { name: 'Joël Kiassumbua', shortName: 'Kiassumbua', position: 'GK', starter: true },
  { name: 'Chancel Mbemba', shortName: 'Mbemba', position: 'DEF', starter: true },
  { name: 'Marcel Tisserand', shortName: 'Tisserand', position: 'DEF', starter: true },
  { name: 'Bope Bokadi', shortName: 'Bokadi', position: 'DEF', starter: true },
  { name: 'Mukau Nkuba', shortName: 'Nkuba', position: 'DEF', starter: true },
  { name: 'Gaël Kakuta', shortName: 'Kakuta', position: 'MID', starter: true },
  { name: 'Paul-José Mpoku', shortName: 'Mpoku', position: 'MID', starter: true },
  { name: 'Dodi Lukebakio', shortName: 'Lukebakio', position: 'MID', starter: true },
  { name: 'Meschack Elia', shortName: 'Elia', position: 'FWD', starter: true },
  { name: 'Yoane Wissa', shortName: 'Wissa', position: 'FWD', starter: true },
  { name: 'Cédric Bakambu', shortName: 'Bakambu', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Leydi Mukonkole', shortName: 'Mukonkole', position: 'GK', starter: false },
  { name: 'Samuel Moutoussamy', shortName: 'Moutoussamy', position: 'MID', starter: false },
  { name: 'Jonathan Bolingi', shortName: 'Bolingi', position: 'FWD', starter: false },
  { name: 'Yvan Neyou', shortName: 'Neyou', position: 'MID', starter: false },
  { name: 'Christian Luyindama', shortName: 'Luyindama', position: 'DEF', starter: false },
  { name: 'Frédéric Nsimba', shortName: 'Nsimba', position: 'FWD', starter: false },
  { name: 'Silas', shortName: 'Silas', position: 'FWD', starter: false },
  { name: 'Nathan Ngoy', shortName: 'N. Ngoy', position: 'MID', starter: false },
  { name: 'Theo Bongonda', shortName: 'Bongonda', position: 'FWD', starter: false },
  { name: 'Clinton Mata', shortName: 'C. Mata', position: 'DEF', starter: false },
];

const ECOSSE: Squad = [
  // Titulaires (4-3-3)
  { name: 'Craig Gordon', shortName: 'C. Gordon', position: 'GK', starter: true },
  { name: 'Jack Hendry', shortName: 'Hendry', position: 'DEF', starter: true },
  { name: 'Grant Hanley', shortName: 'Hanley', position: 'DEF', starter: true },
  { name: 'Scott McKenna', shortName: 'McKenna', position: 'DEF', starter: true },
  { name: 'Aaron Hickey', shortName: 'Hickey', position: 'DEF', starter: true },
  { name: 'Scott McTominay', shortName: 'McTominay', position: 'MID', starter: true },
  { name: 'John McGinn', shortName: 'McGinn', position: 'MID', starter: true },
  { name: 'Billy Gilmour', shortName: 'Gilmour', position: 'MID', starter: true },
  { name: 'Ryan Christie', shortName: 'Christie', position: 'FWD', starter: true },
  { name: 'Lawrence Shankland', shortName: 'Shankland', position: 'FWD', starter: true },
  { name: 'Che Adams', shortName: 'Che Adams', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Zander Clark', shortName: 'Z. Clark', position: 'GK', starter: false },
  { name: 'Robby McCrorie', shortName: 'McCrorie', position: 'GK', starter: false },
  { name: 'Andy Robertson', shortName: 'Robertson', position: 'DEF', starter: false },
  { name: 'Liam Cooper', shortName: 'L. Cooper', position: 'DEF', starter: false },
  { name: 'Kieran Tierney', shortName: 'K. Tierney', position: 'DEF', starter: false },
  { name: 'Kenny McLean', shortName: 'McLean', position: 'MID', starter: false },
  { name: 'Callum McGregor', shortName: 'McGregor', position: 'MID', starter: false },
  { name: 'Ryan Fraser', shortName: 'R. Fraser', position: 'FWD', starter: false },
  { name: 'Stuart Armstrong', shortName: 'Armstrong', position: 'MID', starter: false },
  { name: 'Ryan Jack', shortName: 'R. Jack', position: 'MID', starter: false },
  { name: 'Ross Stewart', shortName: 'R. Stewart', position: 'FWD', starter: false },
  { name: 'Lyndon Dykes', shortName: 'Dykes', position: 'FWD', starter: false },
  { name: 'Kevin Nisbet', shortName: 'Nisbet', position: 'FWD', starter: false },
  { name: 'Oli McBurnie', shortName: 'McBurnie', position: 'FWD', starter: false },
];

const ALLEMAGNE: Squad = [
  // Titulaires (4-2-3-1)
  { name: 'Marc-André ter Stegen', shortName: 'ter Stegen', position: 'GK', starter: true },
  { name: 'Benjamin Henrichs', shortName: 'Henrichs', position: 'DEF', starter: true },
  { name: 'Antonio Rüdiger', shortName: 'Rüdiger', position: 'DEF', starter: true },
  { name: 'Nico Schlotterbeck', shortName: 'Schlotterbeck', position: 'DEF', starter: true },
  { name: 'David Raum', shortName: 'Raum', position: 'DEF', starter: true },
  { name: 'Joshua Kimmich', shortName: 'Kimmich', position: 'MID', starter: true },
  { name: 'Ilkay Gündogan', shortName: 'Gündogan', position: 'MID', starter: true },
  { name: 'Florian Wirtz', shortName: 'Wirtz', position: 'FWD', starter: true },
  { name: 'Jamal Musiala', shortName: 'Musiala', position: 'FWD', starter: true },
  { name: 'Leroy Sané', shortName: 'Sané', position: 'FWD', starter: true },
  { name: 'Kai Havertz', shortName: 'Havertz', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Oliver Baumann', shortName: 'Baumann', position: 'GK', starter: false },
  { name: 'Kevin Trapp', shortName: 'Trapp', position: 'GK', starter: false },
  { name: 'Jonathan Tah', shortName: 'Tah', position: 'DEF', starter: false },
  { name: 'Pascal Groß', shortName: 'P. Groß', position: 'MID', starter: false },
  { name: 'Maximilian Arnold', shortName: 'Arnold', position: 'MID', starter: false },
  { name: 'Robin Gosens', shortName: 'Gosens', position: 'DEF', starter: false },
  { name: 'Thomas Müller', shortName: 'Müller', position: 'FWD', starter: false },
  { name: 'Serge Gnabry', shortName: 'Gnabry', position: 'FWD', starter: false },
  { name: 'Niclas Füllkrug', shortName: 'Füllkrug', position: 'FWD', starter: false },
  { name: 'Deniz Undav', shortName: 'Undav', position: 'FWD', starter: false },
  { name: 'Julian Brandt', shortName: 'Brandt', position: 'MID', starter: false },
  { name: 'Mergim Berisha', shortName: 'Berisha', position: 'FWD', starter: false },
];

const COTE_IVOIRE: Squad = [
  // Titulaires (4-3-3)
  { name: 'Yahia Fofana', shortName: 'Y. Fofana', position: 'GK', starter: true },
  { name: 'Serge Aurier', shortName: 'Aurier', position: 'DEF', starter: true },
  { name: 'Eric Bailly', shortName: 'Bailly', position: 'DEF', starter: true },
  { name: 'Simon Deli', shortName: 'S. Deli', position: 'DEF', starter: true },
  { name: 'Ghislain Konan', shortName: 'Konan', position: 'DEF', starter: true },
  { name: 'Franck Kessié', shortName: 'Kessié', position: 'MID', starter: true },
  { name: 'Ibrahim Sangaré', shortName: 'Sangaré', position: 'MID', starter: true },
  { name: 'Seko Fofana', shortName: 'S. Fofana', position: 'MID', starter: true },
  { name: 'Nicolas Pépé', shortName: 'Pépé', position: 'FWD', starter: true },
  { name: 'Sébastien Haller', shortName: 'Haller', position: 'FWD', starter: true },
  { name: 'Wilfried Zaha', shortName: 'Zaha', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Badra Sangaré', shortName: 'B. Sangaré', position: 'GK', starter: false },
  { name: 'Vito Mannone', shortName: 'Mannone', position: 'GK', starter: false },
  { name: 'Wilfried Singo', shortName: 'Singo', position: 'DEF', starter: false },
  { name: 'Odilon Kossounou', shortName: 'Kossounou', position: 'DEF', starter: false },
  { name: 'Jean-Michaël Seri', shortName: 'J-M. Seri', position: 'MID', starter: false },
  { name: 'Max-Alain Gradel', shortName: 'Gradel', position: 'FWD', starter: false },
  { name: 'Sofiane Diop', shortName: 'S. Diop', position: 'FWD', starter: false },
  { name: 'Jonathan Kodjia', shortName: 'Kodjia', position: 'FWD', starter: false },
  { name: 'Christian Kouamé', shortName: 'Kouamé', position: 'FWD', starter: false },
  { name: 'Wilfried Bony', shortName: 'Bony', position: 'FWD', starter: false },
  { name: 'Ahmed Toure', shortName: 'A. Toure', position: 'FWD', starter: false },
  { name: 'Jeannot Essis', shortName: 'Essis', position: 'FWD', starter: false },
];

const ESPAGNE: Squad = [
  // Titulaires (4-3-3)
  { name: 'Unai Simón', shortName: 'U. Simón', position: 'GK', starter: true },
  { name: 'Dani Carvajal', shortName: 'Carvajal', position: 'DEF', starter: true },
  { name: 'Aymeric Laporte', shortName: 'Laporte', position: 'DEF', starter: true },
  { name: 'Pau Torres', shortName: 'P. Torres', position: 'DEF', starter: true },
  { name: 'Alejandro Balde', shortName: 'Baldé', position: 'DEF', starter: true },
  { name: 'Rodri', shortName: 'Rodri', position: 'MID', starter: true },
  { name: 'Pedri', shortName: 'Pedri', position: 'MID', starter: true },
  { name: 'Gavi', shortName: 'Gavi', position: 'MID', starter: true },
  { name: 'Lamine Yamal', shortName: 'L. Yamal', position: 'FWD', starter: true },
  { name: 'Álvaro Morata', shortName: 'Morata', position: 'FWD', starter: true },
  { name: 'Nico Williams', shortName: 'N. Williams', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'David Raya', shortName: 'Raya', position: 'GK', starter: false },
  { name: 'Álex Remiro', shortName: 'Remiro', position: 'GK', starter: false },
  { name: 'César Azpilicueta', shortName: 'Azpilicueta', position: 'DEF', starter: false },
  { name: 'Robin Le Normand', shortName: 'Le Normand', position: 'DEF', starter: false },
  { name: 'Mikel Merino', shortName: 'Merino', position: 'MID', starter: false },
  { name: 'Fabián Ruiz', shortName: 'F. Ruiz', position: 'MID', starter: false },
  { name: 'Dani Olmo', shortName: 'D. Olmo', position: 'MID', starter: false },
  { name: 'Ferran Torres', shortName: 'F. Torres', position: 'FWD', starter: false },
  { name: 'Mikel Oyarzabal', shortName: 'Oyarzabal', position: 'FWD', starter: false },
  { name: 'Ansu Fati', shortName: 'Ansu Fati', position: 'FWD', starter: false },
  { name: 'Yeremy Pino', shortName: 'Y. Pino', position: 'FWD', starter: false },
  { name: 'Marco Asensio', shortName: 'Asensio', position: 'FWD', starter: false },
  { name: 'Bryan Gil', shortName: 'B. Gil', position: 'FWD', starter: false },
];

const ARABIE_SAOUDITE: Squad = [
  // Titulaires (4-2-3-1)
  { name: 'Mohammed Al-Owais', shortName: 'Al-Owais', position: 'GK', starter: true },
  { name: 'Sultan Al-Ghannam', shortName: 'Al-Ghannam', position: 'DEF', starter: true },
  { name: 'Ali Al-Bulaihi', shortName: 'Al-Bulaihi', position: 'DEF', starter: true },
  { name: 'Hassan Tambakti', shortName: 'Tambakti', position: 'DEF', starter: true },
  { name: 'Yasser Al-Shahrani', shortName: 'Al-Shahrani', position: 'DEF', starter: true },
  { name: 'Mohammed Al-Qasim', shortName: 'Al-Qasim', position: 'MID', starter: true },
  { name: 'Sami Al-Najei', shortName: 'Al-Najei', position: 'MID', starter: true },
  { name: 'Salem Al-Dawsari', shortName: 'S. Al-Dawsari', position: 'FWD', starter: true },
  { name: 'Abdulellah Al-Malki', shortName: 'Al-Malki', position: 'FWD', starter: true },
  { name: 'Firas Al-Buraikan', shortName: 'Al-Buraikan', position: 'FWD', starter: true },
  { name: 'Abdullah Al-Hamdan', shortName: 'Al-Hamdan', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Abdullah Al-Mayouf', shortName: 'Al-Mayouf', position: 'GK', starter: false },
  { name: 'Nawaf Al-Aqidi', shortName: 'Al-Aqidi', position: 'GK', starter: false },
  { name: 'Mohammed Alburayk', shortName: 'Alburayk', position: 'DEF', starter: false },
  { name: 'Saud Abdulhamid', shortName: 'Abdulhamid', position: 'DEF', starter: false },
  { name: 'Ali Al-Hassan', shortName: 'Al-Hassan', position: 'MID', starter: false },
  { name: 'Abdulrahman Al-Obood', shortName: 'Al-Obood', position: 'MID', starter: false },
  { name: 'Abdulrahman Ghareeb', shortName: 'Ghareeb', position: 'FWD', starter: false },
  { name: 'Saleh Al-Shehri', shortName: 'S. Al-Shehri', position: 'FWD', starter: false },
  { name: 'Hattan Bahebri', shortName: 'Bahebri', position: 'FWD', starter: false },
  { name: 'Nasser Al-Dawsari', shortName: 'N. Al-Dawsari', position: 'FWD', starter: false },
  { name: 'Mohammed Al-Shehri', shortName: 'M. Al-Shehri', position: 'FWD', starter: false },
  { name: 'Mohammed Kanno', shortName: 'Kanno', position: 'MID', starter: false },
  { name: 'Riyadh Sharahili', shortName: 'Sharahili', position: 'MID', starter: false },
];

const IRAK: Squad = [
  // Titulaires (4-3-3)
  { name: 'Jalal Hassan', shortName: 'J. Hassan', position: 'GK', starter: true },
  { name: 'Ali Adnan', shortName: 'A. Adnan', position: 'DEF', starter: true },
  { name: 'Rebin Sulaka', shortName: 'Sulaka', position: 'DEF', starter: true },
  { name: 'Ali Faez', shortName: 'A. Faez', position: 'DEF', starter: true },
  { name: 'Saad Natiq', shortName: 'S. Natiq', position: 'DEF', starter: true },
  { name: 'Amjad Kalaf', shortName: 'A. Kalaf', position: 'MID', starter: true },
  { name: 'Aziz Karim', shortName: 'A. Karim', position: 'MID', starter: true },
  { name: 'Hussein Ali', shortName: 'H. Ali', position: 'MID', starter: true },
  { name: 'Bashar Rasan', shortName: 'B. Rasan', position: 'FWD', starter: true },
  { name: 'Mohanad Ali', shortName: 'M. Ali', position: 'FWD', starter: true },
  { name: 'Aymen Hussein', shortName: 'A. Hussein', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Mohammed Hameed', shortName: 'M. Hameed', position: 'GK', starter: false },
  { name: 'Zaid Tahseen', shortName: 'Z. Tahseen', position: 'GK', starter: false },
  { name: 'Mustafa Nadhim', shortName: 'M. Nadhim', position: 'DEF', starter: false },
  { name: 'Ahmed Karimi', shortName: 'A. Karimi', position: 'DEF', starter: false },
  { name: 'Omar Abdulsalam', shortName: 'O. Abdulsalam', position: 'MID', starter: false },
  { name: 'Humam Tariq', shortName: 'H. Tariq', position: 'MID', starter: false },
  { name: 'Ahmed Yasin', shortName: 'A. Yasin', position: 'MID', starter: false },
  { name: 'Mahdi Kamil', shortName: 'M. Kamil', position: 'MID', starter: false },
  { name: 'Ali Al-Hamadi', shortName: 'Al-Hamadi', position: 'FWD', starter: false },
  { name: 'Alaa Abbas', shortName: 'A. Abbas', position: 'FWD', starter: false },
  { name: 'Mashal Abdulrahman', shortName: 'Abdulrahman', position: 'FWD', starter: false },
];

const ANGLETERRE: Squad = [
  // Titulaires (4-3-3)
  { name: 'Jordan Pickford', shortName: 'Pickford', position: 'GK', starter: true },
  { name: 'Trent Alexander-Arnold', shortName: 'Alexander-Arnold', position: 'DEF', starter: true },
  { name: 'John Stones', shortName: 'Stones', position: 'DEF', starter: true },
  { name: 'Marc Guéhi', shortName: 'Guéhi', position: 'DEF', starter: true },
  { name: 'Kieran Trippier', shortName: 'Trippier', position: 'DEF', starter: true },
  { name: 'Declan Rice', shortName: 'D. Rice', position: 'MID', starter: true },
  { name: 'Jude Bellingham', shortName: 'Bellingham', position: 'MID', starter: true },
  { name: 'Phil Foden', shortName: 'Foden', position: 'MID', starter: true },
  { name: 'Bukayo Saka', shortName: 'Saka', position: 'FWD', starter: true },
  { name: 'Harry Kane', shortName: 'H. Kane', position: 'FWD', starter: true },
  { name: 'Marcus Rashford', shortName: 'Rashford', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Sam Johnstone', shortName: 'Johnstone', position: 'GK', starter: false },
  { name: 'James Trafford', shortName: 'Trafford', position: 'GK', starter: false },
  { name: 'Luke Shaw', shortName: 'L. Shaw', position: 'DEF', starter: false },
  { name: 'Harry Maguire', shortName: 'Maguire', position: 'DEF', starter: false },
  { name: 'Ben Chilwell', shortName: 'Chilwell', position: 'DEF', starter: false },
  { name: 'Kobbie Mainoo', shortName: 'Mainoo', position: 'MID', starter: false },
  { name: 'Conor Gallagher', shortName: 'Gallagher', position: 'MID', starter: false },
  { name: 'James Maddison', shortName: 'Maddison', position: 'MID', starter: false },
  { name: 'Jarrod Bowen', shortName: 'Bowen', position: 'FWD', starter: false },
  { name: 'Ollie Watkins', shortName: 'Watkins', position: 'FWD', starter: false },
  { name: 'Raheem Sterling', shortName: 'Sterling', position: 'FWD', starter: false },
  { name: 'Anthony Gordon', shortName: 'Gordon', position: 'FWD', starter: false },
  { name: 'Curtis Jones', shortName: 'C. Jones', position: 'MID', starter: false },
  { name: 'Cole Palmer', shortName: 'C. Palmer', position: 'MID', starter: false },
];

const GHANA: Squad = [
  // Titulaires (4-2-3-1)
  { name: 'Lawrence Ati-Zigi', shortName: 'Ati-Zigi', position: 'GK', starter: true },
  { name: 'Denis Odoi', shortName: 'D. Odoi', position: 'DEF', starter: true },
  { name: 'Daniel Amartey', shortName: 'Amartey', position: 'DEF', starter: true },
  { name: 'Alexander Djiku', shortName: 'Djiku', position: 'DEF', starter: true },
  { name: 'Baba Rahman', shortName: 'B. Rahman', position: 'DEF', starter: true },
  { name: 'Thomas Partey', shortName: 'T. Partey', position: 'MID', starter: true },
  { name: 'Salis Abdul Samed', shortName: 'Abdul Samed', position: 'MID', starter: true },
  { name: 'Mohammed Kudus', shortName: 'Kudus', position: 'FWD', starter: true },
  { name: 'Jordan Ayew', shortName: 'J. Ayew', position: 'FWD', starter: true },
  { name: 'Kamaldeen Sulemana', shortName: 'Sulemana', position: 'FWD', starter: true },
  { name: 'Inaki Williams', shortName: 'I. Williams', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Abdul Manaf Nurudeen', shortName: 'Nurudeen', position: 'GK', starter: false },
  { name: 'Ibrahim Danlad', shortName: 'Danlad', position: 'GK', starter: false },
  { name: 'Gideon Mensah', shortName: 'G. Mensah', position: 'DEF', starter: false },
  { name: 'Tariqe Fosu', shortName: 'T. Fosu', position: 'DEF', starter: false },
  { name: 'Daniel-Kofi Kyereh', shortName: 'Kyereh', position: 'MID', starter: false },
  { name: 'Edmund Addo', shortName: 'E. Addo', position: 'MID', starter: false },
  { name: 'André Ayew', shortName: 'A. Ayew', position: 'FWD', starter: false },
  { name: 'Osman Bukari', shortName: 'Bukari', position: 'FWD', starter: false },
  { name: 'Antoine Semenyo', shortName: 'Semenyo', position: 'FWD', starter: false },
  { name: 'Abdul Fatawu Issahaku', shortName: 'Issahaku', position: 'FWD', starter: false },
  { name: 'Elisha Owusu', shortName: 'E. Owusu', position: 'MID', starter: false },
  { name: 'Joel Fameyeh', shortName: 'Fameyeh', position: 'FWD', starter: false },
  { name: 'Ransford Yeboah', shortName: 'Yeboah', position: 'FWD', starter: false },
  { name: 'Emmanuel Lomotey', shortName: 'Lomotey', position: 'MID', starter: false },
];

const HAITI: Squad = [
  // Titulaires (4-3-3)
  { name: 'Johny Placide', shortName: 'Placide', position: 'GK', starter: true },
  { name: 'Mechack Jérôme', shortName: 'M. Jérôme', position: 'DEF', starter: true },
  { name: 'Donald Guerrier', shortName: 'D. Guerrier', position: 'DEF', starter: true },
  { name: 'Andrew Guelce', shortName: 'Guelce', position: 'DEF', starter: true },
  { name: 'Markus Dvine', shortName: 'Dvine', position: 'DEF', starter: true },
  { name: 'Steeven Saba', shortName: 'Saba', position: 'MID', starter: true },
  { name: 'Kervens Belfort', shortName: 'Belfort', position: 'MID', starter: true },
  { name: 'Jacques Nazon', shortName: 'J. Nazon', position: 'MID', starter: true },
  { name: 'Randy Vilme', shortName: 'Vilme', position: 'FWD', starter: true },
  { name: 'Duckens Nazon', shortName: 'D. Nazon', position: 'FWD', starter: true },
  { name: 'Kevin Lafrance', shortName: 'Lafrance', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Hassan Bichara', shortName: 'Bichara', position: 'GK', starter: false },
  { name: 'Ketleen Guiteau', shortName: 'Guiteau', position: 'GK', starter: false },
  { name: 'Jems Geffrard', shortName: 'Geffrard', position: 'DEF', starter: false },
  { name: 'Rouby Jean-Baptiste', shortName: 'Jean-Baptiste', position: 'DEF', starter: false },
  { name: 'Hans Bourdon', shortName: 'Bourdon', position: 'MID', starter: false },
  { name: 'Frantzdy Pierrot', shortName: 'Pierrot', position: 'FWD', starter: false },
  { name: 'Jhon Sheryl', shortName: 'J. Sheryl', position: 'MID', starter: false },
  { name: 'Clifford Aboagye', shortName: 'Aboagye', position: 'MID', starter: false },
  { name: 'Ricardo Ade', shortName: 'R. Ade', position: 'FWD', starter: false },
  { name: 'Lionel Benjamin', shortName: 'Benjamin', position: 'FWD', starter: false },
  { name: 'Edouard Cissouma', shortName: 'Cissouma', position: 'FWD', starter: false },
  { name: 'Wilde Guerrier', shortName: 'W. Guerrier', position: 'FWD', starter: false },
  { name: 'Gregory Dolce', shortName: 'Dolce', position: 'MID', starter: false },
];

const NORVEGE: Squad = [
  // Titulaires (4-3-3)
  { name: 'Ørjan Nyland', shortName: 'Nyland', position: 'GK', starter: true },
  { name: 'Julian Ryerson', shortName: 'Ryerson', position: 'DEF', starter: true },
  { name: 'Leo Østigård', shortName: 'Østigård', position: 'DEF', starter: true },
  { name: 'Andreas Hanche-Olsen', shortName: 'Hanche-Olsen', position: 'DEF', starter: true },
  { name: 'Birger Meling', shortName: 'Meling', position: 'DEF', starter: true },
  { name: 'Martin Ødegaard', shortName: 'Ødegaard', position: 'MID', starter: true },
  { name: 'Sander Berge', shortName: 'Berge', position: 'MID', starter: true },
  { name: 'Fredrik Aursnes', shortName: 'Aursnes', position: 'MID', starter: true },
  { name: 'Mohamed Elyounoussi', shortName: 'Elyounoussi', position: 'FWD', starter: true },
  { name: 'Erling Haaland', shortName: 'Haaland', position: 'FWD', starter: true },
  { name: 'Alexander Sørloth', shortName: 'Sørloth', position: 'FWD', starter: true },
  // Remplaçants
  { name: 'Rune Jarstein', shortName: 'Jarstein', position: 'GK', starter: false },
  { name: 'Markus Haugen', shortName: 'Haugen', position: 'GK', starter: false },
  { name: 'Kristoffer Ajer', shortName: 'Ajer', position: 'DEF', starter: false },
  { name: 'Patrick Berg', shortName: 'P. Berg', position: 'MID', starter: false },
  { name: 'Morten Thorsby', shortName: 'Thorsby', position: 'MID', starter: false },
  { name: 'Kristian Thorstvedt', shortName: 'Thorstvedt', position: 'MID', starter: false },
  { name: 'Antonio Nusa', shortName: 'Nusa', position: 'FWD', starter: false },
  { name: 'Jens Petter Hauge', shortName: 'Hauge', position: 'FWD', starter: false },
  { name: 'Ola Solbakken', shortName: 'Solbakken', position: 'FWD', starter: false },
  { name: 'Jonas Svensson', shortName: 'Svensson', position: 'DEF', starter: false },
  { name: 'Noah Holm', shortName: 'N. Holm', position: 'FWD', starter: false },
  { name: 'Adrian Pereira', shortName: 'A. Pereira', position: 'FWD', starter: false },
  { name: 'Joshua King', shortName: 'J. King', position: 'FWD', starter: false },
];

export const SQUADS: Record<string, Squad> = {
  bresil: BRESIL,
  maroc: MAROC,
  belgique: BELGIQUE,
  egypte: EGYPTE,
  france: FRANCE,
  senegal: SENEGAL,
  portugal: PORTUGAL,
  'rd-congo': RD_CONGO,
  ecosse: ECOSSE,
  allemagne: ALLEMAGNE,
  'cote-ivoire': COTE_IVOIRE,
  espagne: ESPAGNE,
  'arabie-saoudite': ARABIE_SAOUDITE,
  irak: IRAK,
  angleterre: ANGLETERRE,
  ghana: GHANA,
  haiti: HAITI,
  norvege: NORVEGE,
};

export function getSquad(squadKey: string): Squad {
  return SQUADS[squadKey] ?? [];
}
